name = "Dominium Modpack"
author = "ceduardorodrig"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18f75f0e559fe8a86be9e2f5e08269ec6d5e7eb46b5d50c70b12b44727b1ce8c"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
