name = "Dominium Modpack"
author = "ceduardorodrig"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3a1d79cc3e5ed9694419eeaf790d6bc749d16676010b54feb1444f73ed3ac5f"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
